#:kivy 1.9.1
#:include gui/codelistview.kv
#:include gui/labelrecolorable.kv
#:include gui/commitcontextview.kv

GridLayout:
  id: container
  rows: 2
  cols: 2
  padding: 1
  spacing: 0

  CodeScrollView:
    id: blame_codelines_list
    size_hint: (1.0, 0.66)

  CodeScrollView:
    id: diff_codelines_list
    size_hint: (1.0, 0.66)

  CommitContextView:
    size_hint: (1.0, 0.34)

  CommitContextView:
    size_hint: (1.0, 0.34)