#:kivy 1.9.1
#:include gui/codelistview.kv
#:include gui/commitcontextview.kv

<LabelRecolorable>:
  bg_color: 0, 0, 0
  canvas.before:
    Color:
      rgb: self.bg_color
    Rectangle:
      pos: self.pos
      size: self.size

GridLayout:
  id: container
  rows: 2
  cols: 0
  padding: 1
  spacing: 0

  CodeListView:
    id: codelines_list
    size_hint: (1.0, 0.66)

  CommitContextView:
    size_hint: (1.0, 0.34)