#:kivy 1.9.1

<ButtonTabPanel>:
  bg_color: 1, 1, 1
  height: 50

  canvas.before:
    Color:
      rgb: self.bg_color
    Rectangle:
      pos: self.pos
      size: self.size

  TabPanel:
    id: button_container
    size_hint: (1, None)
    height: self.minimum_height

<TabButton>:
  shorten: True
  shorten_from: 'left'
  size_hint: (None, None)
  width: 200
  height: 25
  padding_x: 2
  text_size: (self.size[0], None)
  halign: 'center'