#:kivy 1.9.1

<CommitBoxView>:
  spacing: 10
  padding: 5

<CommitBox>:
  orientation: 'vertical'
  padding: (10, 5)
  size_hint: (None, None)
  size: (150, 50)
  border_color: 1, 1, 1
  bg_color: 0.3, 0.3, 0.3
  border_width: 2

  BoxLayout:
    Label:
      id: commit_hex

    Label:
      id: commit_date

  Label:
    id: commit_message
    shorten: True
    shorten_from: 'right'
    text_size: self.size
